### ISSUE TITLE
通过tg的bot发送书提示发送失败

### ISSUE THREAD

**Issue by wikilike7** [qcgzxw/ebook-sender-bot#61]
通过tg的bot发送书提示发送失败

反复多试了几次也是一样的情况

**Comment by qcgzxw** [comment]
需要在配置文件填写正确的smtp配置，发送失败一般是发件配置有问题

**Comment by wikilike7** [comment]
> 需要在配置文件填写正确的 smtp 配置，发送失败一般是发件配置有问题

sorry, 我没有说明白，我是说你提供的那个tg上面的bot发送不了书了

**Comment by qcgzxw** [comment]
哦哦，我排查下看看什么问题

**Comment by qcgzxw** [comment]
> > 需要在配置文件填写正确的 smtp 配置，发送失败一般是发件配置有问题
> 
> 
> 
> sorry, 我没有说明白，我是说你提供的那个tg上面的bot发送不了书了

https://t.me/@qcgzxw
方便在tg联系下我吗，我知道tg用户名的话排查起来更快

**Comment by wikilike7** [comment]
> > > 需要在配置文件填写正确的 smtp 配置，发送失败一般是发件配置有问题
> > 
> > 
> > sorry, 我没有说明白，我是说你提供的那个 tg 上面的 bot 发送不了书了
> 
> https://t.me/qcgzxw 方便在 tg 联系下我吗，我知道 tg 用户名的话排查起来更快

我联系你了

顺便说一下，我用bot倒是可以发送，也不会提示失败了，但是很奇怪收不到电子书，我核对了kindle地址和允许的发件人，都没问题，很奇怪
<img width="449" alt="Snipaste_2022-12-06_21-42-53" src="https://user-images.githubusercontent.com/3377226/205928240-c22a6624-420a-4209-a48b-87f66f7fec41.png">

**Comment by qcgzxw** [comment]
> > > > 需要在配置文件填写正确的 smtp 配置，发送失败一般是发件配置有问题
> 
> > > 
> 
> > > 
> 
> > > sorry, 我没有说明白，我是说你提供的那个 tg 上面的 bot 发送不了书了
> 
> > 
> 
> > https://t.me/qcgzxw 方便在 tg 联系下我吗，我知道 tg 用户名的话排查起来更快
> 
> 
> 
> 我联系你了
> 
> 
> 
> 顺便说一下，我用bot倒是可以发送，也不会提示失败了，但是很奇怪收不到电子书，我核对了kindle地址和允许的发件人，都没问题，很奇怪
> 
> <img width="449" alt="Snipaste_2022-12-06_21-42-53" src="https://user-images.githubusercontent.com/3377226/205928240-c22a6624-420a-4209-a48b-87f66f7fec41.png">
> 
> 
> 
> 
> 
> 
> 
> 

你的tg可能是+86，私聊我我收不到消息。

可能是因为我前几天换了发件邮箱，你需要重新添加一下。
发送/start给机器人获取最新邮箱
