### ISSUE TITLE
Ebook Send Bot 不再接受epub格式了吗？

### ISSUE THREAD

**Issue by bosshua** [qcgzxw/ebook-sender-bot#68]
从12月24日开始，发送epub文件时就会收到这段回复：
> kindle只允许接受 [doc|.docx|.rtf|.html|.htm|.pdf|.txt|.azw|.azw1|.azw3|.azw4|.fb2|.lrf|.kfx|.pdb|.lit|.mobi] 类型的文件
请问是取消了这个功能吗？

**Comment by qcgzxw** [comment]
bug已临时修复
